//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Network.DAL.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aducation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aducation()
        {
            this.User_sPersonalData = new HashSet<User_sPersonalData>();
        }
    
        public System.Guid Id { get; set; }
        public string Type { get; set; }
        public string Institution { get; set; }
        public string Specialization { get; set; }
        public Nullable<System.DateTime> StartYear { get; set; }
        public Nullable<System.DateTime> GradYear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_sPersonalData> User_sPersonalData { get; set; }
    }
}
