//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Network.DAL.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aducation
    {
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public string University { get; set; }
        public Nullable<int> StartYear { get; set; }
        public Nullable<int> GradYear { get; set; }
    
        public virtual User User { get; set; }
    }
}
