//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Network.DAL.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public System.Guid Id { get; set; }
        public string Information { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string SenderId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
