//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Network.DAL.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conference()
        {
            this.ListenerConfer = new HashSet<ListenerConfer>();
            this.MembersOfConference = new HashSet<MembersOfConference>();
        }
    
        public System.Guid Id { get; set; }
        public string Thema { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Direction { get; set; }
        public string Details { get; set; }
        public Nullable<bool> Visibility { get; set; }
        public byte[] Requirements { get; set; }
        public byte[] Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListenerConfer> ListenerConfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MembersOfConference> MembersOfConference { get; set; }
    }
}
