//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Network.DAL.EFModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InstitutNetworkContext : DbContext
    {
        public InstitutNetworkContext()
            : base("name=InstitutNetworkContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserRoles> AspNetUserRoles { get; set; }
        public virtual DbSet<Aducation> Aducation { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<ListenerConfer> ListenerConfer { get; set; }
        public virtual DbSet<Conference> Conference { get; set; }
        public virtual DbSet<MembersOfConference> MembersOfConference { get; set; }
        public virtual DbSet<ReportConference> ReportConference { get; set; }
        public virtual DbSet<MemberOfGroup> MemberOfGroup { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<ResourceGroup> ResourceGroup { get; set; }
    }
}
