//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Network.DAL.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportConference
    {
        public System.Guid Id { get; set; }
        public System.Guid ConferenceId { get; set; }
        public byte[] Content { get; set; }
        public string Title { get; set; }
        public string Extension { get; set; }
    
        public virtual Conference Conference { get; set; }
    }
}
