//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Network.DAL.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.MembersOfConference = new HashSet<MembersOfConference>();
            this.MembersOfGroup = new HashSet<MembersOfGroup>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid PersonalDataId { get; set; }
        public System.Guid ContactId { get; set; }
        public Nullable<bool> Visibility { get; set; }
        public string AspUserId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MembersOfConference> MembersOfConference { get; set; }
        public virtual User_sContact User_sContact { get; set; }
        public virtual User_sPersonalData User_sPersonalData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MembersOfGroup> MembersOfGroup { get; set; }
    }
}
